### ISSUE TITLE
Integración en ddclient

### ISSUE THREAD

**Issue by madmalkav** [dondominio/dondns-bash#1]
He creado un PR para integrar el soporte de DonDominio en ddclient, que es una herramienta disponible en los repositorios de la mayoría de las distribuciones. Os lo enlazo por si quereis echar un ojo y sugerir algún cambio

https://github.com/ddclient/ddclient/pull/68

**Comment by mateusan** [comment]
Por nuestra parte, lo vemos todo correcto. Muy buen trabajo.
